/**
 * fileWatcher.ts
 *
 * Wraps `@tauri-apps/plugin-fs` `watch()` with:
 *
 * - Self-write suppression — before every atomic write the caller registers
 *   the target path via `suppressNext()`.  Events for that path are silently
 *   dropped until the suppress window expires, preventing Phing's own renames
 *   from being misidentified as external changes.
 *
 * - Debounced delivery (delayMs: 400) to filter spurious FS noise.
 *
 * - Automatic restart when the vault path changes.
 *
 * The module exports a singleton `vaultWatcher` instance and a pure
 * `contentHash` function used for cheap in-memory vs on-disk comparison.
 */

import { watch, type UnwatchFn } from '@tauri-apps/plugin-fs';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface FileChangeEvent {
  absPath: string;
  kind: 'modify' | 'create' | 'remove';
}

export type FileChangeHandler = (event: FileChangeEvent) => void;

// ── Watcher class ─────────────────────────────────────────────────────────────

export class VaultFileWatcher {
  private unwatchFn: UnwatchFn | null = null;
  /** path → suppress-until timestamp (ms) */
  private readonly suppressMap = new Map<string, number>();

  /**
   * Suppresses change events for `absPath` for the next `windowMs`
   * milliseconds.  Call this immediately before triggering an atomic write
   * to prevent the resulting rename event from being processed as an external
   * modification.
   *
   * Multiple events for the same path within the window are all suppressed —
   * the entry is not consumed on first use, only when it expires.
   */
  suppressNext(absPath: string, windowMs = 2000): void {
    this.suppressMap.set(absPath, Date.now() + windowMs);
  }

  async start(vaultPath: string, onEvent: FileChangeHandler): Promise<void> {
    if (this.unwatchFn) await this.stop();

    this.unwatchFn = await watch(
      vaultPath,
      (rawEvent) => {
        const now = Date.now();

        // Prune expired suppress entries.
        for (const [path, until] of this.suppressMap) {
          if (now >= until) this.suppressMap.delete(path);
        }

        const paths: string[] = Array.isArray(rawEvent.paths) ? rawEvent.paths : [];

        for (const p of paths) {
          // Only care about Markdown notes; skip snapshots and tmp artefacts.
          if (!p.endsWith('.md')) continue;
          if (p.includes('/.phing/')) continue;

          // Skip events generated by our own atomic writes.
          const suppressUntil = this.suppressMap.get(p) ?? 0;
          if (now < suppressUntil) continue;

          onEvent({ absPath: p, kind: resolveEventKind(rawEvent.type) });
        }
      },
      { recursive: true, delayMs: 400 },
    );
  }

  async stop(): Promise<void> {
    if (this.unwatchFn) {
      await this.unwatchFn();
      this.unwatchFn = null;
    }
  }

  get isWatching(): boolean {
    return this.unwatchFn !== null;
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function resolveEventKind(rawType: unknown): FileChangeEvent['kind'] {
  if (typeof rawType !== 'object' || rawType === null) return 'modify';
  const key = Object.keys(rawType as object)[0]?.toLowerCase() ?? '';
  if (key === 'create') return 'create';
  if (key === 'remove' || key === 'delete') return 'remove';
  return 'modify';
}

// ── FNV-1a 32-bit hash ────────────────────────────────────────────────────────
// Pure TypeScript — no native modules.  Fast enough for typical note sizes.
// Used to distinguish genuine external changes from no-op saves.
export function contentHash(str: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h;
}

// ── Module singleton ──────────────────────────────────────────────────────────

/** Shared across App.tsx and noteStore write paths. */
export const vaultWatcher = new VaultFileWatcher();
